server:
  port: 9992
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.pg.bocken.entity

filePath:   F:/work/tup/
nginxPath:  http://localhost:8060/tup/

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db_backen?userUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: 123456